exec-once = hypridle
exec-once = mako
exec-once = waybar
exec-once = fcitx5
exec-once = hyprpaper
exec-once = swayosd-server
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

exec-once = [workspace 1 silent] brave
exec-once = [workspace 4 silent] xdg-terminal-exec --dir="$HOME/.local/share/dotfiles" -e zsh -lic "nvim"
exec-once = [workspace 5 silent] fastmail
exec-once = [workspace 5 silent] signal-desktop-beta
exec-once = [workspace 6 silent] newsflash
